server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: ENC(gc16brBHPNq27HsjaULgKGq00Rz6ZUji)
    password: 123456
    url: jdbc:mysql://127.0.0.1:3309/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: 123456
      username: liao
      queue: zipkin
  storage:
    type: mysql
